import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import cloudRouter from './cloud.js';
let db;
try {
  db = (await import('./db.js')).default;
} catch (error) {
  console.error('[server] database initialization failed', error);
  throw error;
}

const app = express();
const serverDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(serverDir, '../..');
const HOST = process.env.HOST || '127.0.0.1';
const PORT = Number(process.env.PORT || 4000);
console.log('[server] starting...');
console.log(`[server] configured endpoint http://${HOST}:${PORT}`);
app.use(cors({ origin: process.env.CLIENT_ORIGIN || 'http://localhost:5173', credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use('/role-cards', express.static(path.join(projectRoot, 'client/public/role-cards'), { fallthrough: false }));
// Username-session requests are handled by the cloud router. Requests without
// a bearer token fall through to the legacy SQLite-compatible API.
app.use('/api', cloudRouter);
const now = () => new Date().toISOString();
const token = () => crypto.randomBytes(32).toString('base64url');
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
const normalizeRoleName = value => String(value || '').normalize('NFKC').trim();
const roleImageFiles = (() => {
  const dirs = [path.join(projectRoot, 'images'), path.join(projectRoot, 'client/public/role-cards')];
  const files = new Map();
  for (const dir of dirs) {
    try { for (const file of fs.readdirSync(dir)) if (/\.(png|jpe?g|webp)$/i.test(file)) files.set(normalizeRoleName(file.replace(/\.[^.]+$/, '')), file); } catch {}
  }
  return files;
})();
const cardImageUrl = role => {
  const aliases = role.aliases ? String(role.aliases).split(',') : [];
  const candidates = [role.canonical_name, role.name, ...aliases].map(normalizeRoleName).filter(Boolean);
  for (const candidate of candidates) {
    const file = roleImageFiles.get(candidate) || roleImageFiles.get(candidate.replace(/[（(].*[）)]$/, '').trim());
    if (file) return `/role-cards/${encodeURIComponent(file)}`;
  }
  return null;
};
const roleView = r => ({ id:r.id, name:r.name, canonicalName:r.canonical_name, aliases:r.aliases?String(r.aliases).split(',').map(v=>v.trim()).filter(Boolean):[], camp:r.camp, category:r.category, subCategory:r.sub_category, description:r.description, shortDescription:r.short_description||r.description, skillDescription:r.skill_description||r.description, winCondition:r.win_condition, actionPhase:r.action_phase, actionOrder:r.action_order, targetType:r.target_type, maxUses:r.max_uses, isAwakening:!!r.is_awakening, isLimited:!!r.is_limited, isEasterEgg:!!r.is_easter_egg, isCollaboration:!!r.is_collaboration, version:r.version, sourceName:r.source_name, sourceUrl:r.source_url, sourceDate:r.source_date, verifiedAt:r.verified_at, verificationStatus:r.verification_status, icon:r.icon, cardImageUrl:cardImageUrl(r) });
const readToken = (req, kind) => req.headers[`x-${kind}-token`] || req.cookies?.[kind+'Token'] || (req.headers.authorization||'').replace(/^Bearer\s+/i,'');
const gameById = id => db.prepare('SELECT * FROM games WHERE id=?').get(id);
const safeGame = g => { if (!g) return g; const { judge_token_hash, judge_token_created_at, judge_id, ...rest } = g; return rest; };
const judge = (req,res,next) => { const g=gameById(req.params.id); if(!g)return res.status(404).json({error:'牌局不存在'}); const t=readToken(req,'judge'); if(!t || !g.judge_token_hash || hash(t)!==g.judge_token_hash)return res.status(403).json({error:'仅法官可操作'}); req.game=g; req.judgeToken=t; next(); };
const player = (req,res,next) => { const g=gameById(req.params.id); if(!g)return res.status(404).json({error:'牌局不存在'}); const t=readToken(req,'player'); const p=t&&db.prepare('SELECT * FROM players WHERE game_id=? AND player_token_hash=?').get(g.id,hash(t)); if(!p)return res.status(403).json({error:'玩家会话无效'}); db.prepare('UPDATE players SET is_online=1,last_seen_at=? WHERE id=?').run(now(),p.id); req.game=g; req.player=p; next(); };
const judgeSession = (req,res,next) => { const t=readToken(req,'judge'); const g=t&&db.prepare('SELECT * FROM games WHERE judge_token_hash=?').get(hash(t)); if(!g)return res.status(401).json({code:'JUDGE_TOKEN_INVALID',error:'无法验证法官身份'}); req.game=g; next(); };
const logEvent = (gameId,type,description,target=null) => { const g=gameById(gameId); db.prepare('INSERT INTO game_events(game_id,event_type,description,target_player_id,day_number,phase,created_at,created_by) VALUES (?,?,?,?,?,?,?,NULL)').run(gameId,type,description||type,target,g?.day_number||1,g?.phase||'WAITING',now()); };

app.get('/api/health',(req,res)=>res.json({ok:true,service:'night-game-api'}));
app.get('/api/roles',(req,res,next)=>{try { res.json({roles:db.prepare('SELECT * FROM roles WHERE is_active=1 ORDER BY camp,sub_category,name').all().map(roleView)}); } catch (error) { next(error); }});
app.get('/api/roles/:id',(req,res)=>{const r=db.prepare('SELECT * FROM roles WHERE id=? AND is_active=1').get(req.params.id); if(!r)return res.status(404).json({error:'角色不存在'}); res.json({role:roleView(r)});});

app.post('/api/games',(req,res)=>{const p=z.object({name:z.string().trim().min(2).max(60),playerCount:z.number().int().min(4).max(30),roles:z.array(z.object({roleId:z.number().int(),quantity:z.number().int().min(0)}))}).safeParse(req.body); if(!p.success)return res.status(400).json({error:'牌局配置不合法'}); const total=p.data.roles.reduce((s,r)=>s+r.quantity,0); if(total!==p.data.playerCount)return res.status(400).json({error:`身份牌数量需为 ${p.data.playerCount}`}); const requested=[...new Set(p.data.roles.filter(r=>r.quantity>0).map(r=>r.roleId))]; const active=new Set(db.prepare(`SELECT id FROM roles WHERE is_active=1 AND id IN (${requested.map(()=>'?').join(',')||'NULL'})`).all(...requested).map(r=>r.id)); if(requested.some(id=>!active.has(id)))return res.status(400).json({error:'牌局包含不可用的身份牌'}); let code; do{code='WOLF-'+crypto.randomBytes(3).toString('hex').toUpperCase()}while(db.prepare('SELECT 1 FROM games WHERE invite_code=?').get(code)); const judgeToken=token(); const tx=db.transaction(()=>{const g=db.prepare('INSERT INTO games(name,invite_code,player_count,status,created_at,judge_id,judge_token_hash,judge_token_created_at) VALUES (?,?,?,?,?,(SELECT id FROM users LIMIT 1),?,?)').run(p.data.name,code,p.data.playerCount,'WAITING',now(),hash(judgeToken),now()); for(const r of p.data.roles.filter(x=>x.quantity>0))db.prepare('INSERT INTO game_roles(game_id,role_id,quantity) VALUES (?,?,?)').run(g.lastInsertRowid,r.roleId,r.quantity); return g.lastInsertRowid;}); const id=tx(); res.cookie('judgeToken',judgeToken,{httpOnly:true,sameSite:'lax'}); res.status(201).json({game:safeGame(gameById(id)),inviteCode:code,judgeToken,judgeUrl:`/judge/${judgeToken}`,joinUrl:`/join/${code}`}); });
app.get('/api/games/join/:inviteCode',(req,res)=>{const g=db.prepare('SELECT id,name,invite_code,player_count,status,(SELECT COUNT(*) FROM players p WHERE p.game_id=g.id) joined_count FROM games g WHERE invite_code=?').get((req.params.inviteCode||'').toUpperCase()); if(!g)return res.status(404).json({error:'邀请码不存在'}); res.json({game:g,canJoin:g.status==='WAITING'&&g.joined_count<g.player_count});});
app.post('/api/games/join',(req,res)=>{const p=z.object({inviteCode:z.string().trim().min(4),nickname:z.string().trim().min(2).max(20)}).safeParse(req.body); if(!p.success)return res.status(400).json({error:'请输入2-20个字符的玩家姓名'}); const g=db.prepare('SELECT * FROM games WHERE invite_code=?').get(p.data.inviteCode.toUpperCase()); if(!g)return res.status(404).json({error:'邀请码不存在'}); if(g.status!=='WAITING')return res.status(400).json({error:'牌局已开始或结束'}); if(db.prepare('SELECT 1 FROM players WHERE game_id=? AND nickname=?').get(g.id,p.data.nickname))return res.status(409).json({error:'该玩家姓名已存在'}); const playerToken=token(); let info; try { info=db.transaction(()=>{const count=db.prepare('SELECT COUNT(*) c FROM players WHERE game_id=?').get(g.id).c; if(count>=g.player_count) throw Object.assign(new Error('牌局人数已满'),{code:'GAME_FULL'}); return db.prepare('INSERT INTO players(game_id,nickname,seat_number,player_token_hash,joined_at,last_seen_at) VALUES (?,?,?,?,?,?)').run(g.id,p.data.nickname,count+1,hash(playerToken),now(),now()); })(); } catch (error) { if(error.code==='GAME_FULL') return res.status(409).json({code:'GAME_FULL',error:error.message}); if(String(error.message).includes('UNIQUE')) return res.status(409).json({error:'该玩家姓名已存在'}); throw error; } const pl=db.prepare('SELECT id,nickname,seat_number,status,is_ready,is_online,joined_at FROM players WHERE id=?').get(info.lastInsertRowid); res.cookie('playerToken',playerToken,{httpOnly:true,sameSite:'lax'}); res.status(201).json({gameId:g.id,playerToken,player:pl,game:{id:g.id,name:g.name,inviteCode:g.invite_code,playerCount:g.player_count,status:g.status}}); });

app.get('/api/player/me',(req,res)=>{const t=readToken(req,'player'); const p=t&&db.prepare('SELECT * FROM players WHERE player_token_hash=?').get(hash(t)); if(!p)return res.status(403).json({error:'玩家会话无效'}); const g=gameById(p.game_id); db.prepare('UPDATE players SET is_online=1,last_seen_at=? WHERE id=?').run(now(),p.id); const viewed=!!db.prepare('SELECT 1 FROM player_roles WHERE player_id=? AND is_revealed=1').get(p.id); res.json({game:{id:g.id,name:g.name,inviteCode:g.invite_code,playerCount:g.player_count,status:g.status,dayNumber:g.day_number,phase:g.phase},player:{id:p.id,nickname:p.nickname,seatNumber:p.seat_number,status:p.status,isReady:!!p.is_ready,isOnline:true,hasViewedRole:viewed}}); });
app.get('/api/player/state',(req,res)=>{const t=readToken(req,'player'); const p=t&&db.prepare('SELECT * FROM players WHERE player_token_hash=?').get(hash(t)); if(!p)return res.status(403).json({error:'玩家会话无效'}); const g=gameById(p.game_id); db.prepare('UPDATE players SET is_online=1,last_seen_at=? WHERE id=?').run(now(),p.id); const assignment=db.prepare('SELECT pr.is_revealed,r.* FROM player_roles pr JOIN roles r ON r.id=pr.role_id WHERE pr.player_id=?').get(p.id); res.json({game:{id:g.id,name:g.name,inviteCode:g.invite_code,playerCount:g.player_count,status:g.status,dayNumber:g.day_number,phase:g.phase},player:{id:p.id,nickname:p.nickname,seatNumber:p.seat_number,status:p.status,isReady:!!p.is_ready,isOnline:true,hasViewedRole:!!assignment},role:assignment?{...roleView(assignment),isRevealed:!!assignment.is_revealed}:null}); });
app.get('/api/player/my-role',(req,res)=>{const t=readToken(req,'player'); const p=t&&db.prepare('SELECT * FROM players WHERE player_token_hash=?').get(hash(t)); if(!p)return res.status(403).json({error:'玩家会话无效'}); const row=db.prepare('SELECT pr.is_revealed,r.* FROM player_roles pr JOIN roles r ON r.id=pr.role_id WHERE pr.player_id=?').get(p.id); if(!row)return res.status(404).json({error:'身份尚未分配'}); res.json({role:roleView(row),isRevealed:!!row.is_revealed}); });
app.post('/api/player/leave',(req,res)=>{const t=readToken(req,'player'); const p=t&&db.prepare('SELECT id FROM players WHERE player_token_hash=?').get(hash(t)); if(p)db.prepare('UPDATE players SET is_online=0,last_seen_at=? WHERE id=?').run(now(),p.id); res.clearCookie('playerToken').json({ok:true}); });

app.get('/api/games/:id',(req,res,next)=>{const g=gameById(req.params.id); if(!g)return res.status(404).json({error:'牌局不存在'}); const jt=readToken(req,'judge'),pt=readToken(req,'player'); const isJudge=!!(jt&&g.judge_token_hash&&hash(jt)===g.judge_token_hash); const mine=pt&&db.prepare('SELECT id,nickname,seat_number,status,is_ready,is_online FROM players WHERE game_id=? AND player_token_hash=?').get(g.id,hash(pt)); if(!isJudge&&!mine)return res.status(403).json({error:'无权查看该牌局'}); const players=db.prepare('SELECT id,nickname,seat_number,is_ready,is_online,status FROM players WHERE game_id=? ORDER BY seat_number').all(g.id); const roles=db.prepare('SELECT gr.role_id,gr.quantity,r.* FROM game_roles gr JOIN roles r ON r.id=gr.role_id WHERE gr.game_id=?').all(g.id).map(r=>({...roleView(r),role_id:r.role_id,quantity:r.quantity})); res.json({game:safeGame(g),players,roles,isJudge,isPlayer:!!mine,player:mine||null}); });
// Deliberately exposes only the configured deck. Player-role assignments never leave the server here.
app.get('/api/games/:id/public-roles',(req,res)=>{const g=gameById(req.params.id);if(!g)return res.status(404).json({error:'牌局不存在'});const jt=readToken(req,'judge'),pt=readToken(req,'player');const isJudge=!!(jt&&g.judge_token_hash&&hash(jt)===g.judge_token_hash);const mine=pt&&db.prepare('SELECT id FROM players WHERE game_id=? AND player_token_hash=?').get(g.id,hash(pt));if(!isJudge&&!mine)return res.status(403).json({error:'无权查看该牌局'});const roles=db.prepare('SELECT gr.role_id,gr.quantity,r.* FROM game_roles gr JOIN roles r ON r.id=gr.role_id WHERE gr.game_id=? ORDER BY r.camp,r.sub_category,r.name').all(g.id).map(r=>{const role=roleView(r);return {roleId:role.id,name:role.name,canonicalName:role.canonicalName,count:r.quantity,quantity:r.quantity,camp:role.camp,category:role.category,subCategory:role.subCategory,shortDescription:role.shortDescription,skillDescription:role.skillDescription,winCondition:role.winCondition,icon:role.icon,cardImageUrl:role.cardImageUrl};});res.json({gameId:g.id,total:roles.reduce((sum,r)=>sum+r.quantity,0),roles});});
app.get('/api/games/:id/players',judge,(req,res)=>res.json({players:db.prepare('SELECT id,nickname,seat_number,is_ready,is_online,status FROM players WHERE game_id=? ORDER BY seat_number').all(req.game.id)}));
app.post('/api/games/:id/start',judge,(req,res)=>{const g=req.game; const count=db.prepare('SELECT COUNT(*) c FROM players WHERE game_id=?').get(g.id).c; const total=db.prepare('SELECT COALESCE(SUM(quantity),0) c FROM game_roles WHERE game_id=?').get(g.id).c; if(g.status!=='WAITING')return res.status(400).json({error:'当前状态不可开始'}); if(count!==g.player_count)return res.status(400).json({error:`还需要 ${g.player_count-count} 名玩家`}); if(total!==g.player_count)return res.status(400).json({error:'身份牌数量不匹配'}); db.transaction(()=>{const list=[];for(const r of db.prepare('SELECT role_id,quantity FROM game_roles WHERE game_id=?').all(g.id))for(let i=0;i<r.quantity;i++)list.push(r.role_id);for(let i=list.length-1;i>0;i--){const j=crypto.randomInt(i+1);[list[i],list[j]]=[list[j],list[i]]}const ps=db.prepare('SELECT id FROM players WHERE game_id=? ORDER BY seat_number').all(g.id);db.prepare('DELETE FROM player_roles WHERE game_id=?').run(g.id);ps.forEach((p,i)=>db.prepare('INSERT INTO player_roles(game_id,player_id,role_id,assigned_at) VALUES (?,?,?,?)').run(g.id,p.id,list[i],now()));db.prepare('UPDATE games SET status=?,phase=?,day_number=?,started_at=? WHERE id=?').run('ROLE_ASSIGNED','NIGHT',1,now(),g.id)})(); logEvent(g.id,'GAME_START','身份已随机分配'); res.json({ok:true}); });
app.post('/api/games/:id/shuffle',judge,(req,res)=>{if(req.game.status==='FINISHED')return res.status(400).json({error:'牌局已结束'}); db.transaction(()=>{db.prepare('DELETE FROM player_roles WHERE game_id=?').run(req.game.id);db.prepare('UPDATE games SET status=? WHERE id=?').run('WAITING',req.game.id)})(); res.json({ok:true});});
app.get('/api/games/:id/my-role',player,(req,res)=>{const row=db.prepare('SELECT pr.is_revealed,r.* FROM player_roles pr JOIN roles r ON r.id=pr.role_id WHERE pr.player_id=?').get(req.player.id); if(!row)return res.status(404).json({error:'身份尚未分配'}); res.json({role:roleView(row),isRevealed:!!row.is_revealed});});
app.post('/api/games/:id/reveal',player,(req,res)=>{const row=db.prepare('SELECT id FROM player_roles WHERE player_id=?').get(req.player.id); if(!row)return res.status(404).json({error:'身份尚未分配'}); db.prepare('UPDATE player_roles SET is_revealed=1 WHERE id=?').run(row.id); res.json({ok:true});});
app.get('/api/games/:id/roles',judge,(req,res)=>res.json({assignments:db.prepare('SELECT p.seat_number,p.nickname,r.name,r.camp,r.icon,pr.is_revealed FROM player_roles pr JOIN players p ON p.id=pr.player_id JOIN roles r ON r.id=pr.role_id WHERE pr.game_id=? ORDER BY p.seat_number').all(req.game.id)}));
app.get('/api/games/:id/judge',judge,(req,res)=>{const g=req.game;const players=db.prepare('SELECT p.id,p.game_id,p.nickname,p.seat_number,p.status,p.is_ready,p.is_online,p.joined_at,p.last_seen_at,p.death_type,p.died_at,r.name role_name,r.camp role_camp,r.category role_category,r.sub_category role_sub_category,r.icon role_icon FROM players p LEFT JOIN player_roles pr ON pr.player_id=p.id LEFT JOIN roles r ON r.id=pr.role_id WHERE p.game_id=? ORDER BY p.seat_number').all(g.id);const badge=db.prepare('SELECT b.*,p.nickname,p.seat_number FROM badges b LEFT JOIN players p ON p.id=b.player_id WHERE b.game_id=? AND b.is_active=1').get(g.id);const events=db.prepare('SELECT * FROM game_events WHERE game_id=? ORDER BY created_at DESC').all(g.id);res.json({game:safeGame(g),players,badge,events});});
app.post('/api/games/:id/phase',judge,(req,res)=>{const phase=req.body?.phase;if(!['NIGHT','DAY'].includes(phase))return res.status(400).json({error:'无效阶段'});const g=req.game;const day=phase==='NIGHT'&&g.phase==='DAY'?g.day_number+1:g.day_number;db.prepare('UPDATE games SET phase=?,day_number=?,status=? WHERE id=?').run(phase,day,'PLAYING',g.id);logEvent(g.id,phase==='NIGHT'?'NIGHT_START':'DAY_START',`第${day}${phase==='NIGHT'?'夜':'天'}`);res.json({ok:true,dayNumber:day,phase});});
app.post('/api/games/:id/badge',judge,(req,res)=>{const {action,playerId}=req.body||{};const g=req.game;if(!['award','transfer','destroy'].includes(action))return res.status(400).json({error:'无效操作'});if(action==='destroy'){db.prepare('UPDATE badges SET is_active=0,destroyed_at=? WHERE game_id=? AND is_active=1').run(now(),g.id);db.prepare('INSERT INTO badge_events(game_id,event_type,created_at) VALUES (?,?,?)').run(g.id,'DESTROY',now());logEvent(g.id,'BADGE_DESTROY','撕毁警徽');}else{if(!playerId)return res.status(400).json({error:'请选择玩家'});db.prepare('UPDATE badges SET is_active=0,transferred_at=? WHERE game_id=? AND is_active=1').run(now(),g.id);db.prepare('INSERT INTO badges(game_id,player_id,is_active,awarded_at) VALUES (?,?,1,?)').run(g.id,playerId,now());db.prepare('INSERT INTO badge_events(game_id,player_id,event_type,target_player_id,created_at) VALUES (?,?,?,?,?)').run(g.id,playerId,action==='award'?'AWARD':'TRANSFER',playerId,now());logEvent(g.id,action==='award'?'BADGE_AWARD':'BADGE_TRANSFER',action==='award'?'授予警徽':'转移警徽',playerId);}res.json({ok:true});});
app.post('/api/games/:id/player-status',judge,(req,res)=>{const {playerId,status,reason}=req.body||{};const map={EXILED:'EXILE',KILLED:'NIGHT_KILL',SELF_DESTRUCTED:'SELF_DESTRUCT',ALIVE:null};if(!Object.prototype.hasOwnProperty.call(map,status))return res.status(400).json({error:'无效状态'});const p=db.prepare('SELECT * FROM players WHERE id=? AND game_id=?').get(playerId,req.game.id);if(!p)return res.status(404).json({error:'玩家不存在'});const dt=map[status];db.prepare('UPDATE players SET status=?,death_type=?,died_at=? WHERE id=?').run(status,dt,dt?now():null,p.id);if(dt)db.prepare('INSERT INTO death_events(game_id,player_id,day_number,phase,death_type,reason,created_at) VALUES (?,?,?,?,?,?,?)').run(req.game.id,p.id,req.game.day_number,req.game.phase,dt,reason||'',now());logEvent(req.game.id,dt?'PLAYER_'+status:'PLAYER_REVIVED',dt?`${p.seat_number}号 ${p.nickname} ${status}`:`恢复${p.nickname}存活`,p.id);res.json({ok:true});});
app.post('/api/games/:id/finish',judge,(req,res)=>{const winner=['GOOD','WEREWOLF','NEUTRAL','DRAW'].includes(req.body?.winner)?req.body.winner:null;db.prepare('UPDATE games SET status=?,winner=?,ended_at=? WHERE id=?').run('FINISHED',winner,now(),req.game.id);logEvent(req.game.id,'GAME_END',winner?`宣布${winner}胜利`:'牌局结束');res.json({ok:true});});
app.get('/api/games/:id/events',judge,(req,res)=>res.json({events:db.prepare('SELECT * FROM game_events WHERE game_id=? ORDER BY created_at').all(req.game.id),deaths:db.prepare('SELECT * FROM death_events WHERE game_id=? ORDER BY created_at').all(req.game.id),badgeEvents:db.prepare('SELECT * FROM badge_events WHERE game_id=? ORDER BY created_at').all(req.game.id)}));
app.get('/api/games/:id/replay',judge,(req,res)=>res.json({game:req.game,timeline:db.prepare('SELECT * FROM game_events WHERE game_id=? ORDER BY created_at').all(req.game.id)}));
app.get('/api/judge/game',(req,res)=>{const t=readToken(req,'judge');const g=t&&db.prepare('SELECT * FROM games WHERE judge_token_hash=?').get(hash(t));if(!g)return res.status(401).json({code:'JUDGE_TOKEN_INVALID',error:'无法验证法官身份'});res.json({game:safeGame(g)});});
app.get('/api/judge/state',judgeSession,(req,res)=>{const g=req.game;const players=db.prepare('SELECT p.id,p.game_id,p.nickname,p.seat_number,p.status,p.is_ready,p.is_online,p.joined_at,p.last_seen_at,p.death_type,p.died_at,r.name role_name,r.camp role_camp,r.category role_category,r.sub_category role_sub_category,r.icon role_icon FROM players p LEFT JOIN player_roles pr ON pr.player_id=p.id LEFT JOIN roles r ON r.id=pr.role_id WHERE p.game_id=? ORDER BY p.seat_number').all(g.id);const badge=db.prepare('SELECT b.*,p.nickname,p.seat_number FROM badges b LEFT JOIN players p ON p.id=b.player_id WHERE b.game_id=? AND b.is_active=1').get(g.id);const events=db.prepare('SELECT * FROM game_events WHERE game_id=? ORDER BY created_at DESC').all(g.id);const selectedRoles=db.prepare('SELECT gr.role_id,gr.quantity,r.name,r.camp,r.icon FROM game_roles gr JOIN roles r ON r.id=gr.role_id WHERE gr.game_id=? ORDER BY r.camp,r.sub_category,r.name').all(g.id);res.json({game:safeGame(g),players,badge,events,selectedRoles});});
app.get('/api/judge/players',judgeSession,(req,res)=>res.json({players:db.prepare('SELECT id,nickname,seat_number,status,is_ready,is_online FROM players WHERE game_id=? ORDER BY seat_number').all(req.game.id)}));
app.get('/api/judge/roles',judgeSession,(req,res)=>res.json({assignments:db.prepare('SELECT p.seat_number,p.nickname,r.name,r.camp,r.icon,pr.is_revealed FROM player_roles pr JOIN players p ON p.id=pr.player_id JOIN roles r ON r.id=pr.role_id WHERE pr.game_id=? ORDER BY p.seat_number').all(req.game.id)}));
app.post('/api/judge/start',judgeSession,(req,res,next)=>{req.params.id=req.game.id; next();},(req,res)=>res.status(307).set('Location',`/api/games/${req.game.id}/start`).end());
for (const [name,path] of [['shuffle','shuffle'],['badge','badge'],['death','player-status'],['events','events'],['finish','finish']]) app.all(`/api/judge/${name}`,judgeSession,(req,res)=>res.status(307).set('Location',`/api/games/${req.game.id}/${path}`).end());

app.use((error,req,res,next)=>{ console.error('[server] request failed',error); if (res.headersSent) return next(error); res.status(500).json({error:'服务器内部错误'}); });
const server = app.listen(PORT,HOST,()=>console.log(`[server] listening on http://${HOST}:${PORT}`));
server.on('error',error=>{ console.error('[server] listen failed',error); process.exitCode=1; });
