import db from './db.js';
const defs={
GOOD:{VILLAGER:['平民','老流氓','旋涡平民'],CORE_GOD:['预言家','女巫','猎人','守卫','白痴','骑士','摄梦人','魔术师'],ADVANCED_GOD:['纯白之女','守墓人','猎魔人','奇迹商人','定序王子','魔镜少女','流光伯爵','驯熊师','赏金猎人','通灵师','占卜师','乌鸦','圣光使者','圣光骑士'],AWAKENED_GOD:['觉醒预言家','觉醒女巫','觉醒猎人','觉醒守卫','觉醒愚者','觉醒摄梦人','觉醒骑士','觉醒孤独少女']},
WEREWOLF:{NORMAL_WOLF:['狼人'],SPECIAL_WOLF:['狼王','白狼王','狼美人','隐狼','石像鬼','恶灵骑士','血月使徒','噩梦之影','蚀时狼妃','狼巫','蚀日侍女','种狼','恶夜骑士（格拉海德）'],AWAKENED_WOLF:['觉醒狼王','觉醒狼美人','觉醒隐狼','觉醒石像鬼','刺客白狼王']},
NEUTRAL:{CLASSIC_NEUTRAL:['丘比特（爱神）','盗贼','咒狐','炸弹人','暗恋者','野孩子','混血儿','单身狗','不详人'],COLLAB_NEUTRAL:['许仙寻香魅影','白蛇预言家']}
};
const icons=['🔮','🧪','🏹','🛡️','✨','⚔️','🌙','🎩','🐺','👑','💋','🕶️','🗿','🗡️','🌕','👁️','⏱️','🧙','☀️','🧬','🔪','💘','🗝️','🦊','💣','💌','🐾','❔','🌸','🐍','👤']; let iconI=0; const now=new Date().toISOString();
const sql=`INSERT INTO roles(name,canonical_name,aliases,camp,category,sub_category,description,short_description,skill_description,win_condition,action_phase,action_order,target_type,max_uses,is_awakening,is_limited,is_easter_egg,is_collaboration,version,source_name,source_url,source_date,verified_at,verification_status,icon,is_active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(name) DO UPDATE SET camp=excluded.camp,category=excluded.category,sub_category=excluded.sub_category,description=excluded.description,skill_description=excluded.skill_description,win_condition=excluded.win_condition,updated_at=excluded.updated_at`;
const stmt=db.prepare(sql); const versionStmt=db.prepare(`INSERT INTO role_versions(role_id,version_name,skill_description,rule_description,source_url,source_name,effective_date,is_current,created_at) SELECT id,?,?,?,?,?,?,1,? FROM roles WHERE name=? AND NOT EXISTS (SELECT 1 FROM role_versions rv WHERE rv.role_id=roles.id AND rv.version_name=?)`); let count=0; const tx=db.transaction(()=>{for(const camp of Object.keys(defs))for(const sub of Object.keys(defs[camp]))for(const name of defs[camp][sub]){const desc=name==='预言家'?'每晚查验一名玩家的阵营。':name==='女巫'?'拥有解药和毒药，各限一次。':name==='狼人'?'夜间共同选择袭击目标。':`${name}按当前板子规则发动技能。`; const easter=name==='刺客白狼王'; const collab=sub==='COLLAB_NEUTRAL'; stmt.run(name,name,name==='血月使徒'?'赤月使徒':null,camp,camp==='GOOD'?(sub==='VILLAGER'?'VILLAGER':'GOD'):camp==='WEREWOLF'?'WOLF':'THIRD_PARTY',sub,desc,desc,desc,camp==='GOOD'?'好人阵营获胜。':camp==='WEREWOLF'?'狼人阵营获胜。':'依据当前板子规则获胜。','NIGHT',10,'ONE_PLAYER','EVERY_NIGHT',sub.startsWith('AWAKENED')?1:0,sub.startsWith('COLLAB')?1:0,easter?1:0,collab?1:0,'2026.08','狼人杀官方正版角色资料','https://langrensha.com','2026-08-29',now,'UNVERIFIED',icons[iconI++%icons.length],1,now,now); const id=db.prepare('SELECT id FROM roles WHERE name=?').get(name).id; versionStmt.run('2026.08',desc,desc,'https://langrensha.com','狼人杀官方正版角色资料','2026-08-29',now,name,'2026.08'); count++}}); tx(); console.log(`Seeded ${count} roles`);
